### ISSUE TITLE
请教 安装 这个模块, 依赖 了 哪个包 ?

### ISSUE THREAD

**Issue by ccdos** [cysnake4713/odoosoft_wechat_enterprise#1]
请教 安装 这个模块, 依赖 了 哪个包 ?

安装时遇到了错误

from wechatpy.enterprise.exceptions import InvalidCorpIdException
from wechatpy.enterprise import WeChatClient, WeChatCrypto, parse_message, create_reply
from wechatpy.exceptions import InvalidSignatureException

**Comment by cysnake4713** [comment]
wechatpy这个包,
